name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: [ '3.1', '3.2', '3.3' ]
        gemfile: [ 'gemfiles/rails_6.1.gemfile', 'gemfiles/rails_7.0.gemfile', 'gemfiles/rails_7.1.gemfile' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --gemfile ${{ matrix.gemfile }}
      - name: Run tests
        run: |
          bundle exec appraisal ${{ matrix.gemfile | split: '/' | last | split: '.' | first }} rspec
